/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserAssignment = IDL.Record({
  'moduleIds' : IDL.Vec(IDL.Text),
  'userId' : IDL.Text,
});
export const CompletionRecord = IDL.Record({
  'id' : IDL.Nat,
  'moduleId' : IDL.Nat,
  'completedAt' : IDL.Int,
  'userName' : IDL.Text,
  'userId' : IDL.Principal,
  'initials' : IDL.Text,
  'signatureData' : IDL.Text,
});
export const AppUser = IDL.Record({
  'id' : IDL.Text,
  'permission' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : IDL.Text,
  'loginSource' : IDL.Text,
  'email' : IDL.Text,
  'loginAt' : IDL.Int,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TrainingModule = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'googleDocUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignModulesToUser' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'createAppUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createModule' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAppUser' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteModule' : IDL.Func([IDL.Nat], [], []),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(UserAssignment)], ['query']),
  'getAllCompletions' : IDL.Func([], [IDL.Vec(CompletionRecord)], ['query']),
  'getAppUser' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
  'getAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
  'getAssignmentsForUser' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCompletionsByModule' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CompletionRecord)],
      ['query'],
    ),
  'getModule' : IDL.Func([IDL.Nat], [IDL.Opt(TrainingModule)], ['query']),
  'getModuleCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getModules' : IDL.Func([], [IDL.Vec(TrainingModule)], ['query']),
  'getMyCompletions' : IDL.Func([], [IDL.Vec(CompletionRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCompletedModule' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerGoogleUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setModuleCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitCompletion' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPublicCompletionForUser' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getPublicCompletionLinks' : IDL.Func([], [IDL.Vec(IDL.Tuple([IDL.Nat, IDL.Text]))], ['query']),
  'updateAppUserPermission' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateModule' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserAssignment = IDL.Record({
    'moduleIds' : IDL.Vec(IDL.Text),
    'userId' : IDL.Text,
  });
  const CompletionRecord = IDL.Record({
    'id' : IDL.Nat,
    'moduleId' : IDL.Nat,
    'completedAt' : IDL.Int,
    'userName' : IDL.Text,
    'userId' : IDL.Principal,
    'initials' : IDL.Text,
    'signatureData' : IDL.Text,
  });
  const AppUser = IDL.Record({
    'id' : IDL.Text,
    'permission' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : IDL.Text,
    'loginSource' : IDL.Text,
    'email' : IDL.Text,
    'loginAt' : IDL.Int,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TrainingModule = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'googleDocUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignModulesToUser' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'createAppUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createModule' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAppUser' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteModule' : IDL.Func([IDL.Nat], [], []),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(UserAssignment)], ['query']),
    'getAllCompletions' : IDL.Func([], [IDL.Vec(CompletionRecord)], ['query']),
    'getAppUser' : IDL.Func([IDL.Text], [IDL.Opt(AppUser)], ['query']),
    'getAppUsers' : IDL.Func([], [IDL.Vec(AppUser)], ['query']),
    'getAssignmentsForUser' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCompletionsByModule' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CompletionRecord)],
        ['query'],
      ),
    'getModule' : IDL.Func([IDL.Nat], [IDL.Opt(TrainingModule)], ['query']),
    'getModuleCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getModules' : IDL.Func([], [IDL.Vec(TrainingModule)], ['query']),
    'getMyCompletions' : IDL.Func([], [IDL.Vec(CompletionRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCompletedModule' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerGoogleUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setModuleCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitCompletion' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPublicCompletionForUser' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getPublicCompletionLinks' : IDL.Func([], [IDL.Vec(IDL.Tuple([IDL.Nat, IDL.Text]))], ['query']),
    'updateAppUserPermission' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateModule' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };