/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'id' : string,
  'permission' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : string,
  'loginSource' : string,
  'email' : string,
  'loginAt' : bigint,
  'department' : string,
}
export interface CompletionRecord {
  'id' : bigint,
  'moduleId' : bigint,
  'completedAt' : bigint,
  'userName' : string,
  'userId' : Principal,
  'initials' : string,
  'signatureData' : string,
}
export interface TrainingModule {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'description' : string,
  'googleDocUrl' : string,
}
export interface UserAssignment {
  'moduleIds' : Array<string>,
  'userId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignModulesToUser' : ActorMethod<[string, Array<string>], undefined>,
  'createAppUser' : ActorMethod<[string, string, string, string], string>,
  'createModule' : ActorMethod<[string, string, string], bigint>,
  'deleteAppUser' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteCompletion' : ActorMethod<[bigint], undefined>,
  'deleteModule' : ActorMethod<[bigint], undefined>,
  'getAllAssignments' : ActorMethod<[], Array<UserAssignment>>,
  'getAllCompletions' : ActorMethod<[], Array<CompletionRecord>>,
  'getAppUser' : ActorMethod<[string], [] | [AppUser]>,
  'getAppUsers' : ActorMethod<[], Array<AppUser>>,
  'getAssignmentsForUser' : ActorMethod<[string], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getCompletionsByModule' : ActorMethod<[bigint], Array<CompletionRecord>>,
  'getModule' : ActorMethod<[bigint], [] | [TrainingModule]>,
  'getModuleCategories' : ActorMethod<[], Array<[string, string]>>,
  'getModules' : ActorMethod<[], Array<TrainingModule>>,
  'getMyCompletions' : ActorMethod<[], Array<CompletionRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasCompletedModule' : ActorMethod<[bigint], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerGoogleUser' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setModuleCategory' : ActorMethod<[string, string], undefined>,
  'submitCompletion' : ActorMethod<[bigint, string, string, string], bigint>,
  'submitPublicCompletionForUser' : ActorMethod<[bigint, string, string, string, string], bigint>,
  'getPublicCompletionLinks' : ActorMethod<[], Array<[bigint, string]>>,
  'updateAppUserPermission' : ActorMethod<[string, string], undefined>,
  'updateModule' : ActorMethod<[bigint, string, string, string], undefined>,
  'approveUser' : ActorMethod<[string, string], undefined>,
  'bootstrapAdmin' : ActorMethod<[string], undefined>,
  'claimOwnership' : ActorMethod<[string], boolean>,
  'getUserByEmail' : ActorMethod<[string], [] | [AppUser]>,
  'rejectUser' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];